class ErrorCodes:
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    ROLE_NOT_ASSIGNED = "ROLE_NOT_ASSIGNED"
    COMPANY_PENDING = "COMPANY_PENDING"
    COMPANY_REJECTED = "COMPANY_REJECTED"
    CODE_EXPIRED = "CODE_EXPIRED"
    INVALID_CODE = "INVALID_CODE"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"