class ErrorCodes:
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED"
    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"

    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"
    EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND"
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    PASSWORD_INCORRECT = "PASSWORD_INCORRECT"
    PASSWORDS_DO_NOT_MATCH = "PASSWORDS_DO_NOT_MATCH"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    USER_BLOCKED = "USER_BLOCKED"
    USER_HAS_COMPANY = "USER_HAS_COMPANY"

    INVALID_CODE = "INVALID_CODE"
    CODE_EXPIRED = "CODE_EXPIRED"
    CODE_ALREADY_USED = "CODE_ALREADY_USED"
    CODE_NOT_FOUND = "CODE_NOT_FOUND"
    RESEND_COOLDOWN_ACTIVE = "RESEND_COOLDOWN_ACTIVE"

    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    ROLE_NOT_ASSIGNED = "ROLE_NOT_ASSIGNED"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"

    COMPANY_NOT_FOUND = "COMPANY_NOT_FOUND"
    COMPANY_PENDING = "COMPANY_PENDING"
    COMPANY_APPROVED = "COMPANY_APPROVED"
    COMPANY_REJECTED = "COMPANY_REJECTED"
    COMPANY_CERTIFICATE_INVALID = "COMPANY_CERTIFICATE_INVALID"
    COMPANY_SUSPENDED = "COMPANY_SUSPENDED"
    

    NIT_ALREADY_EXISTS = "NIT_ALREADY_EXISTS"

    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_DELETE_FAILED = "FILE_DELETE_FAILED"
    INVALID_FILE = "INVALID_FILE"

    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    PRODUCT_ALREADY_EXISTS = "PRODUCT_ALREADY_EXISTS"
    PRODUCT_OUT_OF_STOCK = "PRODUCT_OUT_OF_STOCK"
    PRODUCT_IMAGE_NOT_FOUND = "PRODUCT_IMAGE_NOT_FOUND"

    CATALOG_NOT_FOUND = "CATALOG_NOT_FOUND"

    CATALOG_ATTRIBUTE_NOT_FOUND = "CATALOG_ATTRIBUTE_NOT_FOUND"
    CATALOG_ATTRIBUTE_ALREADY_EXISTS = "CATALOG_ATTRIBUTE_ALREADY_EXISTS"
    CATALOG_ATTRIBUTE_OPTION_NOT_FOUND = "CATALOG_ATTRIBUTE_OPTION_NOT_FOUND"
    CATALOG_ATTRIBUTE_OPTION_ALREADY_EXISTS = "CATALOG_ATTRIBUTE_OPTION_ALREADY_EXISTS"
    CATALOG_ATTRIBUTE_CATALOG_MISMATCH = "CATALOG_ATTRIBUTE_CATALOG_MISMATCH"
    CATALOG_ATTRIBUTE_TYPE_MISMATCH = "CATALOG_ATTRIBUTE_TYPE_MISMATCH"
    CATALOG_ATTRIBUTE_IN_USE = "CATALOG_ATTRIBUTE_IN_USE"
    CATALOG_ATTRIBUTE_INACTIVE = "CATALOG_ATTRIBUTE_INACTIVE"

    PRODUCT_ATTRIBUTE_INVALID = "PRODUCT_ATTRIBUTE_INVALID"
    VARIANT_COMBINATION_INVALID = "VARIANT_COMBINATION_INVALID"
    VARIANT_COMBINATION_DUPLICATE = "VARIANT_COMBINATION_DUPLICATE"
    VARIANT_OPTION_MISMATCH = "VARIANT_OPTION_MISMATCH"
    VARIANT_AXIS_ROLE_INVALID = "VARIANT_AXIS_ROLE_INVALID"
    VARIANT_ALREADY_DELETED = "VARIANT_ALREADY_DELETED"

    VARIANT_NOT_FOUND = "VARIANT_NOT_FOUND"
    VARIANT_COLOR_ALREADY_EXISTS = "VARIANT_COLOR_ALREADY_EXISTS"
    VARIANT_SPECIFICATION_NOT_FOUND = "VARIANT_SPECIFICATION_NOT_FOUND"
    VARIANT_SPECIFICATION_ALREADY_EXISTS = "VARIANT_SPECIFICATION_ALREADY_EXISTS"
    VARIANT_IMAGE_NOT_FOUND = "VARIANT_IMAGE_NOT_FOUND"
    COLOR_NOT_FOUND = "COLOR_NOT_FOUND"
    SPECIFICATION_TEMPLATE_NOT_FOUND = "SPECIFICATION_TEMPLATE_NOT_FOUND"
    SPECIFICATION_TEMPLATE_CATALOG_MISMATCH = "SPECIFICATION_TEMPLATE_CATALOG_MISMATCH"

    ADVERTISEMENT_NOT_FOUND = "ADVERTISEMENT_NOT_FOUND"
    ADVERTISEMENT_IMAGE_REQUIRED = "ADVERTISEMENT_IMAGE_REQUIRED"

    CART_NOT_FOUND = "CART_NOT_FOUND"
    CART_ITEM_NOT_FOUND = "CART_ITEM_NOT_FOUND"
    CART_EMPTY = "CART_EMPTY"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"

    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    INVALID_ORDER_STATUS_TRANSITION = "INVALID_ORDER_STATUS_TRANSITION"
    ORDER_ALREADY_CANCELLED = "ORDER_ALREADY_CANCELLED"

    RETURN_NOT_FOUND = "RETURN_NOT_FOUND"
    RETURN_NOT_ELIGIBLE = "RETURN_NOT_ELIGIBLE"
    RETURN_ALREADY_REQUESTED = "RETURN_ALREADY_REQUESTED"
    RETURN_ALREADY_RESOLVED = "RETURN_ALREADY_RESOLVED"
    INVALID_RETURN_ACTION = "INVALID_RETURN_ACTION"
    ORDER_ITEM_NOT_FOUND = "ORDER_ITEM_NOT_FOUND"

    SHIPPING_CARRIER_NOT_FOUND = "SHIPPING_CARRIER_NOT_FOUND"
    SHIPPING_CARRIER_ALREADY_EXISTS = "SHIPPING_CARRIER_ALREADY_EXISTS"
    SHIPPING_CARRIER_INACTIVE = "SHIPPING_CARRIER_INACTIVE"

    FAVORITE_ALREADY_EXISTS = "FAVORITE_ALREADY_EXISTS"
    FAVORITE_NOT_FOUND = "FAVORITE_NOT_FOUND"

    ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND"
    ADDRESS_REQUIRED = "ADDRESS_REQUIRED"

    WALLET_NOT_FOUND = "WALLET_NOT_FOUND"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    INVALID_AMOUNT = "INVALID_AMOUNT"
    WALLET_TRANSACTION_NOT_FOUND = "WALLET_TRANSACTION_NOT_FOUND"
    RECHARGE_NOT_CORRECTABLE = "RECHARGE_NOT_CORRECTABLE"
    RECHARGE_ALREADY_CORRECTED = "RECHARGE_ALREADY_CORRECTED"

    PURCHASE_NOT_ALLOWED = "PURCHASE_NOT_ALLOWED"

    REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND"
    REVIEW_ALREADY_EXISTS = "REVIEW_ALREADY_EXISTS"
    REVIEW_NOT_ELIGIBLE = "REVIEW_NOT_ELIGIBLE"

    BANK_ACCOUNT_NOT_FOUND = "BANK_ACCOUNT_NOT_FOUND"
    BANK_ACCOUNT_IN_USE = "BANK_ACCOUNT_IN_USE"

    PAYOUT_NOT_FOUND = "PAYOUT_NOT_FOUND"
    PAYOUT_ALREADY_EXISTS = "PAYOUT_ALREADY_EXISTS"
    PAYOUT_ALREADY_PAID = "PAYOUT_ALREADY_PAID"
    PAYOUT_NO_BANK_ACCOUNT = "PAYOUT_NO_BANK_ACCOUNT"
    PAYOUT_NO_VALID_SALES = "PAYOUT_NO_VALID_SALES"
    PAYOUT_INVALID_PERIOD = "PAYOUT_INVALID_PERIOD"

    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
    INVALID_REPORT_TARGET = "INVALID_REPORT_TARGET"
    REPORT_ALREADY_RESOLVED = "REPORT_ALREADY_RESOLVED"

    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"

    DATABASE_ERROR = "DATABASE_ERROR"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"