"""new columns, product and product variant

Revision ID: 452a48b9604a
Revises: f2d117420ea5
Create Date: 2026-07-20 19:15:29.107540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452a48b9604a'
down_revision: Union[str, Sequence[str], None] = 'f2d117420ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('has_variants', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'has_variants')
    op.drop_column('product_variants', 'color')
    # ### end Alembic commands ###
