"""add table colors for product

Revision ID: 47e5c2531ece
Revises: 995dc22bc53a
Create Date: 2026-07-20 20:25:13.613536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e5c2531ece'
down_revision: Union[str, Sequence[str], None] = '995dc22bc53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hex_color', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('product_variants', sa.Column('color_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'product_variants', 'color_variants', ['color_id'], ['id'])
    op.drop_column('product_variants', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.drop_column('product_variants', 'color_id')
    op.drop_table('color_variants')
    # ### end Alembic commands ###
