"""initial migration

Revision ID: 73329b46162a
Revises: 
Create Date: 2026-08-10 04:39:40.007911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73329b46162a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('color_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hex_color', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('specification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('catalog_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fullName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('tell', sa.String(length=50), nullable=False),
    sa.Column('profileImagen', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nameCompany', sa.String(length=50), nullable=False),
    sa.Column('addressCompany', sa.String(length=100), nullable=False),
    sa.Column('CompanyNIT', sa.String(length=50), nullable=False),
    sa.Column('CompanyNITDV', sa.String(length=1), nullable=False),
    sa.Column('CompanyLogo', sa.String(length=255), nullable=True),
    sa.Column('CompanyBanner', sa.String(length=255), nullable=True),
    sa.Column('CompanyCertificate', sa.String(length=255), nullable=True),
    sa.Column('CompanyCertificateStatus', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='companycertificateenum'), nullable=False),
    sa.Column('CompanyStatus', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('event_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('type', sa.Enum('RESET_PASSWORD', 'VERIFY_EMAIL', 'CHANGE_EMAIL', name='type_code_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_codes_user_type', 'event_codes', ['user_id', 'type'], unique=False)
    op.create_table('refreshToken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('user_created', 'user_updated', 'user_upgraded', 'user_blocked', 'user_unblocked', 'user_deleted', 'company_created', 'company_approved', 'company_rejected', 'company_blocked', 'company_unblocked', name='admin_activity_action'), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('target_company_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_company_id'], ['company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_enable', sa.Boolean(), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('has_variants', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_specifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('specification_template_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['specification_template_id'], ['specification_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('color_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color_variants.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variant_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variant_specifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('specification_template_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['specification_template_id'], ['specification_templates.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant_specifications')
    op.drop_table('product_variant_images')
    op.drop_table('product_variants')
    op.drop_table('product_specifications')
    op.drop_table('product_images')
    op.drop_table('products')
    op.drop_table('admin_activities')
    op.drop_table('refreshToken')
    op.drop_index('idx_codes_user_type', table_name='event_codes')
    op.drop_table('event_codes')
    op.drop_table('company')
    op.drop_table('users')
    op.drop_table('specification_templates')
    op.drop_table('roles')
    op.drop_table('color_variants')
    op.drop_table('catalog')
    # ### end Alembic commands ###
