"""add table variantSpecification

Revision ID: 995dc22bc53a
Revises: 20ec3a0277c6
Create Date: 2026-07-20 20:06:47.795262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995dc22bc53a'
down_revision: Union[str, Sequence[str], None] = '20ec3a0277c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variant_specifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('specification_template_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['specification_template_id'], ['specification_templates.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variant_specifications')
    # ### end Alembic commands ###
