"""add order_number (friendly reference) to orders

Revision ID: d9a6b3f4c8e1
Revises: c5d8e3a71f42
Create Date: 2026-08-17 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a6b3f4c8e1'
down_revision: Union[str, Sequence[str], None] = 'c5d8e3a71f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # GENERATED BY DEFAULT AS IDENTITY: Postgres asigna automaticamente
    # 1, 2, 3... tanto a las filas ya existentes como a las nuevas (no
    # hace falta backfill manual) - ver ModelOrder.py > order_number.
    op.add_column(
        'orders',
        sa.Column(
            'order_number',
            sa.Integer(),
            sa.Identity(start=1, increment=1),
            nullable=False,
        ),
    )
    op.create_unique_constraint('uq_orders_order_number', 'orders', ['order_number'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('uq_orders_order_number', 'orders', type_='unique')
    op.drop_column('orders', 'order_number')
