"""upgrade table user

Revision ID: f2d117420ea5
Revises: e9df71b65db9
Create Date: 2026-07-19 19:11:35.623904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d117420ea5'
down_revision: Union[str, Sequence[str], None] = 'e9df71b65db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileImagen', sa.String(length=255), nullable=True))
    op.drop_column('users', 'Photho')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Photho', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'profileImagen')
    # ### end Alembic commands ###
